#%RAML 1.0 Trait
headers:
  client_id:
    description: Client Id Token for accessing the API
    type: string
    required: true
  client_secret:
    description: Client Secret Token for accessing the API
    type: string
    required: true
