#%RAML 1.0 NamedExample
value:
  exception:
    transactionId: "23e40985-451a-4e4f-b605-5ce7a8d181bf"
    exceptionCode: "EL-123"
    timeStamp:  "2012-04-23T18:25:43.511Z"
    message: "System Error"
    reason:  "Error occurred"